title: ARIA Protocol
description: The Semantic Standard for AI Agents
theme: null
remote_theme: null
plugins: []
exclude:
  - /vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
